

version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/authelia.conf:/etc/nginx/authelia.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - authelia
      - servera
      - serverb
    networks:
      dmz:
        ipv4_address: 172.16.30.4
      neta:
        ipv4_address: 172.16.10.3
      netb:
        ipv4_address: 172.16.20.3

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./authelia/config:/config
    expose:
      - 9091
    depends_on:
      - redis
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - AUTHELIA_JWT_SECRET="iTPw0iXo1Cw1KrXFtUYgTRTBqzBRphOUJVqwi0rKaHrW2lWKkFB4GHv2TgI0l9RLgI+snWPloUiJdkwwTQIYMA=="
      - AUTHELIA_SESSION_SECRET="Z1Q1jmAVpkvcdcK+SaKx3LZuwVSvHn892aKbEJ0JuoDR9h6quNtfgcyvzV5SrfOHH4uRLxUeCVIWALEqbhkSIw=="
    networks:
      dmz:
        ipv4_address: 172.16.30.2

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis:/data
    expose:
      - 6379
    networks:
      dmz:
        ipv4_address: 172.16.30.3

  servera:
    image: httpd:latest
    container_name: servera
    expose:
      - '80'
    networks:
      neta:
        ipv4_address: 172.16.10.10

  serverb:
    image: httpd:latest
    container_name: serverb
    expose:
      - '80'
    networks:
      netb:
        ipv4_address: 172.16.20.10

networks:
  neta:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1
  netb:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.20.0/24
          gateway: 172.16.20.1
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.30.0/24
          gateway: 172.16.30.1
volumes:
  redis:
