jwt_secret: "kmlLLq9o5Mmy02k1JeI1zRVGCMNhep9kNQCp4HECzC4="
#default_redirection_url: 'https://192.168.30.1'

server:
  address: 'tcp://:9091'
 # port: 9091
#identity_validation:
#  reset_password:
#    enabled: false

log:
  level: 'debug'

totp:
  issuer: 'authelia.local'
  period: 30
  digits: 6
  algorithm: 'sha1'

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    - domain: '192.168.30.1'
      policy: 'two_factor'
      networks:
        - '192.168.30.0/24'
    - domain: '192.168.30.1'
      resources:
        - '^/servera(/.*)?$'
      policy: 'two_factor'
      networks:
        - '192.168.10.0/24'
        - '172.16.30.0/24'
      subject:
        - 'user:usera'
#      default_redirection_url: 'http://192.168.30.1/servera'
    - domain: '192.168.30.1'
      resources:
        - '^/serverb(/.*)?$'
      policy: 'two_factor'
      networks:
        - '192.168.20.0/24'
        - '172.16.30.0/24'
      subject:
        - 'user:userb'
#      default_redirection_url: 'http://192.168.30.1/serverb'

session:
  name: 'authelia_session'
#  inactivity: 5m
#  remember_me: 1M
  secret: 'Z1Q1jmAVpkvcdcK+SaKx3LZuwVSvHn892aKbEJ0JuoDR9h6quNtfgcyvzV5SrfOHH4uRLxUeCVIWALEqbhkSIw=='
#  expiration: 1h
  same_site: 'lax'
  cookies:
    - domain: '192.168.30.1'
      name: 'authelia_session'
      authelia_url: 'https://192.168.30.1'
      default_redirection_url: 'https://192.168.30.1/verify'
      expiration: '1h'
      inactivity: '5m'
#      remember_me_duration: '1w'
#      same_site: "lax"
  redis:
    host: 'redis'
    port: 6379
storage:
  encryption_key: '13bd56c47b48c6be40504596e09b2419b744465625fa13aa94f02b8c946ce5c9b6ec6f6b2af65634c5af278d4cb2a3ff7c4a13d28d904ef26aabe0ba9a68d1de'
  local:
    path: '/config/db.sqlite3'
notifier:
  filesystem:
    filename: '/config/notification.txt'
#  smtp:
#    username: 'vocongkhanhhg2004@gmail.com'
#    password: 'hrjsfizxzhyopzro'
#    host: "smtp.gmail.com"
#    port: 587
#    address: 'submission://smtp.gmail.com:587'
#    sender: 'vocongkhanhhg2004@gmail.com'
#    subject: '[Authelia] Notification for Authentication'
#    startup_check_address: 'congkhanh.infosec@gmail.com'
